# Project: BMP_HideData_Steganografia
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o HideData_BMP_R.o
LINKOBJ  = main.o HideData_BMP_R.o
LIBS     = -L"C:/R_PC/Programy/DevCpp/Dev-Cpp/MinGW64/lib" -L"C:/R_PC/Programy/DevCpp/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/R_PC/Programy/DevCpp/Dev-Cpp/MinGW64/include" -I"C:/R_PC/Programy/DevCpp/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/R_PC/Programy/DevCpp/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/R_PC/Programy/DevCpp/Dev-Cpp/MinGW64/include" -I"C:/R_PC/Programy/DevCpp/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/R_PC/Programy/DevCpp/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/R_PC/Programy/DevCpp/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = BMP_HideData_Steganografia.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

HideData_BMP_R.o: HideData_BMP_R.cpp
	$(CPP) -c HideData_BMP_R.cpp -o HideData_BMP_R.o $(CXXFLAGS)
